// https://trajbrowser.arc.nasa.gov/traj_browser.php?maxMag=25&maxOCC=4&chk_target_list=on&target_list=Mars&mission_class=oneway&mission_type=rendezvous&LD1=2010&LD2=2040&maxDT=2.5&DTunit=yrs&maxDV=7.0&min=DT&wdw_width=365&submit=Search#a_load_results

module.exports = [
   {
     "Name": "Mars",
     "Earth_Departure_Year": "2011",
     "Earth_Departure_Month": "12",
     "Earth_Departure_Day": "17",
     "Dest_Arrival_Year": "2012",
     "Dest_Arrival_Month": "06",
     "Dest_Arrival_Day": "26",
     "Duration_days": 192,
     "C3 (km2/s2)": 19.4,
     "Abs DLA (degs)": 26,
     "Injection DV (km/s)": 4.07,
     "Post-injection DV (km/s)": 2.25,
     "Total_DV": 6.33,
     "Route": "EM"
  },
  {
    "Name": "Mars",
    "Earth_Departure_Year": "2014",
    "Earth_Departure_Month": "02",
    "Earth_Departure_Day": "08",
    "Dest_Arrival_Year": "2014",
    "Dest_Arrival_Month": "08",
    "Dest_Arrival_Day": "03",
    "Duration_days": 176,
    "C3 (km2/s2)": 29.2,
    "Abs DLA (degs)": 17,
    "Injection DV (km/s)": 4.48,
    "Post-injection DV (km/s)": 1.95,
    "Total_DV": 6.43,
    "Route": "EM"
 },
  {
    "Name": "Mars",
    "Earth_Departure_Year": "2016",
    "Earth_Departure_Month": "04",
    "Earth_Departure_Day": "02",
    "Dest_Arrival_Year": "2016",
    "Dest_Arrival_Month": "08",
    "Dest_Arrival_Day": "24",
    "Duration_days": 144,
    "C3 (km2/s2)": 26.1,
    "Abs DLA (degs)": 2,
    "Injection DV (km/s)": 4.35,
    "Post-injection DV (km/s)": 2.21,
    "Total_DV": 6.56,
    "Route": "EM"
 },
 {
   "Name": "Mars",
   "Earth_Departure_Year": "2018",
   "Earth_Departure_Month": "06",
   "Earth_Departure_Day": "11",
   "Dest_Arrival_Year":"2018",
   "Dest_Arrival_Month": "10",
   "Dest_Arrival_Day":"01",
   "Duration_days": 112,
   "C3 (km2/s2)": 24,
   "Abs DLA (degs)": 28,
   "Injection DV (km/s)": 4.27,
   "Post-injection DV (km/s)": 2.37,
   "Total_DV": 6.64,
   "Route": "EM"
},
 {
   "Name": "Mars",
   "Earth_Departure_Year": "2020",
   "Earth_Departure_Month": "08",
   "Earth_Departure_Day": "19",
   "Dest_Arrival_Year": "2020",
   "Dest_Arrival_Month": "12",
   "Dest_Arrival_Day": "25",
   "Duration_days": 128,
   "C3 (km2/s2)": 27.8,
   "Abs DLA (degs)": 11,
   "Injection DV (km/s)": 4.42,
   "Post-injection DV (km/s)": 1.77,
   "Total_DV": 6.19,
   "Route": "EM"
},
{
  "Name": "Mars",
  "Earth_Departure_Year": "2022",
  "Earth_Departure_Month": "09",
  "Earth_Departure_Day": "26",
  "Dest_Arrival_Year": "2023",
  "Dest_Arrival_Month": "03",
  "Dest_Arrival_Day": "05",
  "Duration_days": 160,
  "C3 (km2/s2)": 24.9,
  "Abs DLA (degs)": 14,
  "Injection DV (km/s)": 4.3,
  "Post-injection DV (km/s)": 2.12,
  "Total_DV": 6.43,
  "Route": "EM"
},
{
  "Name": "Mars",
  "Earth_Departure_Year": "2024",
  "Earth_Departure_Month": "11",
  "Earth_Departure_Day": "02",
  "Dest_Arrival_Year": "2025",
  "Dest_Arrival_Month": "04",
  "Dest_Arrival_Day": "27",
  "Duration_days": 176,
  "C3 (km2/s2)": 25.9,
  "Abs DLA (degs)": 25,
  "Injection DV (km/s)": 4.34,
  "Post-injection DV (km/s)": 2.44,
  "Total_DV": 6.78,
  "Route": "EM"
},
{
  "Name": "Mars",
  "Earth_Departure_Year": "2026",
  "Earth_Departure_Month": "12",
  "Earth_Departure_Day": "10",
  "Dest_Arrival_Year": "2027",
  "Dest_Arrival_Month": "06",
  "Dest_Arrival_Day": "20",
  "Duration_days": 192,
  "C3 (km2/s2)": 26.5,
  "Abs DLA (degs)": 26,
  "Injection DV (km/s)": 4.37,
  "Post-injection DV (km/s)": 1.98,
  "Total_DV": 6.35,
  "Route": "EM"
},
{
  "Name": "Mars",
  "Earth_Departure_Year": "2029",
  "Earth_Departure_Month": "01",
  "Earth_Departure_Day": "16",
  "Dest_Arrival_Year": "2029",
  "Dest_Arrival_Month": "07",
  "Dest_Arrival_Day": "11",
  "Duration_days": 176,
  "C3 (km2/s2)": 24.3,
  "Abs DLA (degs)": 22,
  "Injection DV (km/s)": 4.28,
  "Post-injection DV (km/s)": 2.45,
  "Total_DV": 6.73,
  "Route": "EM"
},
{
  "Name": "Mars",
  "Earth_Departure_Year": "2031",
  "Earth_Departure_Month": "03",
  "Earth_Departure_Day": "11",
  "Dest_Arrival_Year": "2031",
  "Dest_Arrival_Month": "08",
  "Dest_Arrival_Day": "18",
  "Duration_days": 160,
  "C3 (km2/s2)": 27.1,
  "Abs DLA (degs)": 7,
  "Injection DV (km/s)": 4.39,
  "Post-injection DV (km/s)": 2.02,
  "Total_DV": 6.42,
  "Route": "EM"
},
 {
   "Name": "Mars",
   "Earth_Departure_Year": "2033",
   "Earth_Departure_Month": "05",
   "Earth_Departure_Day": "19",
   "Dest_Arrival_Year": "2033",
   "Dest_Arrival_Month": "09",
   "Dest_Arrival_Day": "24",
   "Duration_days": 128,
   "C3 (km2/s2)": 28,
   "Abs DLA (degs)": 19,
   "Injection DV (km/s)": 4.43,
   "Post-injection DV (km/s)": 1.89,
   "Total_DV": 6.33,
   "Route": "EM"
},
{
  "Name": "Mars",
  "Earth_Departure_Year": "2035",
  "Earth_Departure_Month": "07",
  "Earth_Departure_Day": "28",
  "Dest_Arrival_Year": "2035",
  "Dest_Arrival_Month": "11",
  "Dest_Arrival_Day": "17",
  "Duration_days": 112,
  "C3 (km2/s2)": 27.9,
  "Abs DLA (degs)": 23,
  "Injection DV (km/s)": 4.43,
  "Post-injection DV (km/s)": 2.11,
  "Total_DV": 6.54,
  "Route": "EM"
},
 {
   "Name": "Mars",
   "Earth_Departure_Year": "2037",
   "Earth_Departure_Month": "11",
   "Earth_Departure_Day": "19",
   "Dest_Arrival_Year": "2038",
   "Dest_Arrival_Month": "02",
   "Dest_Arrival_Day": "10",
   "Duration_days": 144,
   "C3 (km2/s2)": 31.9,
   "Abs DLA (degs)": 5,
   "Injection DV (km/s)": 4.59,
   "Post-injection DV (km/s)": 1.93,
   "Total_DV": 6.52,
   "Route": "EM"
},
 {
   "Name": "Mars",
   "Earth_Departure_Year": "2039",
   "Earth_Departure_Month": "10",
   "Earth_Departure_Day": "27",
   "Dest_Arrival_Year": "2040",
   "Dest_Arrival_Month": "04",
   "Dest_Arrival_Day": "20",
   "Duration_days": 176,
   "C3 (km2/s2)": 32,
   "Abs DLA (degs)": 20,
   "Injection DV (km/s)": 4.59,
   "Post-injection DV (km/s)": 1.85,
   "Total_DV": 6.44,
   "Route": "EM"
}
]
